// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrnTKLzArc3xbBXQ8GFi_gnc3ijDUYcaI',
    appId: '1:217096996997:web:c8b17453986715f6f4c1ec',
    messagingSenderId: '217096996997',
    projectId: 'fir-crud-f18cf',
    authDomain: 'fir-crud-f18cf.firebaseapp.com',
    storageBucket: 'fir-crud-f18cf.appspot.com',
    measurementId: 'G-0E3PRPSHGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1gzvwJu_lAnNYQUBO1gBtFn8rYY2OGXI',
    appId: '1:217096996997:android:f71292df3d277606f4c1ec',
    messagingSenderId: '217096996997',
    projectId: 'fir-crud-f18cf',
    storageBucket: 'fir-crud-f18cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWU0933SC2s4ry32ByYmAu-GwvSSDD84',
    appId: '1:217096996997:ios:379be1af77e55a55f4c1ec',
    messagingSenderId: '217096996997',
    projectId: 'fir-crud-f18cf',
    storageBucket: 'fir-crud-f18cf.appspot.com',
    iosClientId: '217096996997-2jcqbn12e9g56ioqt464aq7v1chr5s0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAWU0933SC2s4ry32ByYmAu-GwvSSDD84',
    appId: '1:217096996997:ios:379be1af77e55a55f4c1ec',
    messagingSenderId: '217096996997',
    projectId: 'fir-crud-f18cf',
    storageBucket: 'fir-crud-f18cf.appspot.com',
    iosClientId: '217096996997-2jcqbn12e9g56ioqt464aq7v1chr5s0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrnTKLzArc3xbBXQ8GFi_gnc3ijDUYcaI',
    appId: '1:217096996997:web:a3071dbf699114a1f4c1ec',
    messagingSenderId: '217096996997',
    projectId: 'fir-crud-f18cf',
    authDomain: 'fir-crud-f18cf.firebaseapp.com',
    storageBucket: 'fir-crud-f18cf.appspot.com',
    measurementId: 'G-MKJPFZ49SY',
  );
}
